CREATE DATABASE posts;

CREATE TABLE usuarios (
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL,
	rol VARCHAR(10) NOT NULL
);

CREATE TABLE post (
	id INT PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(100) NOT NULL,
	texto VARCHAR(1000) NOT NULL,
	fecha DATE DEFAULT CURRENT_TIMESTAMP,
	autor VARCHAR(30) NOT NULL,
	imagen VARCHAR(1000) NOT NULL
);

CREATE TABLE comentario (
	id INT PRIMARY KEY AUTO_INCREMENT,
	texto VARCHAR(1000) NOT NULL,
	id_usuario INT NOT NULL,
	id_post INT NOT NULL,
	fecha DATE DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(id_usuario) REFERENCES usuarios(id)
);
