<!DOCTYPE HTML>
<html lang="es">
    <head>
        <title>Login</title>
    </head>
    <body>
    
        <form action="index.php?login" method="post">
            <input type="text" name="username" placeholder="nombre de usuario"/><br>
            <input type="password" name="pass" placeholder="contraseña"/><br>
            <input type="submit" value="Entrar"/>
        </form>
        <a href="index.php?register">Registrarse</a>
    </body>
</html>