<html lang="es">
    <head>
        <title>Register</title>
    </head>
    <body>
    
    <form action="index.php?newUser" method="post">
        <input type="text" name="username" placeholder="nombre de usuario"/><br>
        <input type="password" name="pass" placeholder="contraseña"/><br>
        <input type="password" name="pass2" placeholder="contraseña"/><br>
        <input type="email" name="correo" placeholder="correo electronico"/><br>
        
        <input type="submit" value="Registrarse"/>
    </form>
    
    </body>
</html>