<!DOCTYPE html>
<html lang="es">
<head>
	<title>Edición de post</title>
	<meta charset="utf-8">
</head>
<body>
	
	

	<h1>Edición post:</h1>
	<?php
	echo '<form action="index.php?posts" method="post" enctype="multipart/form-data">
		<label for="titulo">Título: </label>
		<input type="text" name="editTitulo" placeholder="Título" value="'.$post->getTitulo().'">
		<br>
		<label for="texto">Texto: </label>
		<textarea type="text" name="editTexto" rows="10" cols="50">'.$post->getTexto().'</textarea type="text">
		<br>
		<label for="fecha">Fecha: </label>
		<input type="date" name="editFecha" value="'.$post->getFecha().'">
		<br>
		<label for="autor">Autor: </label>
		<input type="text" name="editAutor" placeholder="Autor" value="'.$post->getAutor().'">
		<br>
		<label for="imagen">URL imagen: </label>
		<input type="file" name="editImagen" placeholder="URL imagen" value="'.$post->getImagen().'">
		<br>
		<input type="submit" value="Editar" name="editPost">
		<input type="hidden" name="id" value="'.$post->getId().'">
	</form>';
	?>
</body>
</html>