<!DOCTYPE html>
<html lang="es">
	<head>
		<title>Mi lista de peliculas</title>
		<meta charset="utf-8"/>
		<style type="text/css">
			a {
				text-decoration: none;
				color: red;
			}

			#paginacion ul {
				list-style-type: none;
			}

			#paginacion li {
				display: inline;
			}
		</style>
	</head>
	<body>

		<?php 

		if(isset($_SESSION['error'])){
			echo '<script >alert("'.$_SESSION['error'].'")</script>';
			unset($_SESSION['error']);
		}

		if(!$_SESSION['u']) {
		?>
		<form action="index.php?user" method="post">
			<input type="text" name="username" placeholder="nombre de usuario">
			<input type="password" name="password" placeholder="Contraseña">
			<input type="submit" value="Entrar">
		</form>
		<a href="index.php?user&register">Registrarme</a>

		<?php
		}else {
		
		echo '<h2>Bienvenido '.$_SESSION['u']->getUsername().' - Rol: '.$_SESSION['u']->getRol().' - <a href="index.php?user&logout">Salir</a></h2>';
		}

		if($_SESSION['u']->getRol() == 'admin') {
		?>
		<h1>Creación post:</h1>

		<form action="index.php?posts" method="post" enctype="multipart/form-data">
			<label for="titulo">Título: </label>
			<input type="text" name="titulo" placeholder="Título" required>
			<br>
			<label for="texto">Texto: </label>
			<textarea name="texto" rows="10" cols="50" placeholder="Escriba el texto aquí:"></textarea>
			<br>
			<label for="fecha">Fecha: </label>
			<input type="date" name="fecha">
			<br>
			<label for="autor">Autor: </label>
			<input type="text" name="autor" placeholder="Autor">
			<br>
			<label for="imagen">URL imagen: </label>
			<input type="file" name="imagen" placeholder="URL imagen">
			<br>
			<input type="submit" value="Crear" name="post">
		</form>

		<h1>Modificar roles de los usuarios: </h1>
		<ul>
		<?php
		// Me sale solo la modificación en el último elemento. ¿En que fallo?
			foreach ($users as $user) {
				echo '<li>Usuario: '.$user->getUsername().' - Rol: '.$user->getRol().'</li>';
				//setcookie('user', $user->getUsername());
				if($user->getRol() == 'admin') {
					echo '<form action="index.php?user&rol" method="post">
					<input type="hidden" name="id" value="'.$user->getId().'">
					<input type="submit" name="cambiarRol" value="user">
				</form>';
				}else {
					echo '<form action="index.php?user&rol" method="post">
					<input type="hidden" name="id" value="'.$user->getId().'">
					<input type="submit" name="cambiarRol" value="admin">
				</form>';
				}
				
			}
		}
		?>
		</ul>
		<h1>Mi lista de post con comentarios: </h1>

		<form action="index.php" method="post">
			<input type="text" name="buscador" placeholder="Titulo para la búsqueda">
			<input type="submit" name="buscar" value="Busca">
		</form>

		<ul>
		<?php

		foreach ($posts as $post) {
			echo '<li>Título: '.$post->getTitulo().' - Texto: '.$post->getTexto().' - Fecha: '.$post->getFecha().' - Autor: '.$post->getAutor().' - Imagen: '.$post->getImagen().'</li>';
			echo '<br/>';
			echo '<button><a href="index.php?comentarios&create">Crear comentario</a></button>';

			// Panel de administración para editar post o artículos.
			if($_SESSION['u']->getRol() == 'admin') {
				// Me sale solo la modificación en el último elemento. ¿En que fallo?
				//$r =  $post->getTitulo();
				//setcookie('name', $r);
				echo '<button><a href="index.php?posts&edit='.$post->getId().'">Editar post</a></button>';
			}

			// Comporbar que es un comentario el array para mostrar los comentarios de cada post.
			if(is_array($post->getComentarios())) {
				echo '<ul>';
				$comentarios = $post->getComentarios();
				// Listar comentarios de cada post.
				foreach ($comentarios as $comentario) {
					// Comprobar el post para listarlo.
					if(($comentario->getIdPost()) == ($post->getId())) {
						echo '<li>Texto: '.$comentario->getTexto().' - Id usuario: '.$comentario->getIdUsuario().' - Fecha: '.$comentario->getFecha().'</li>';
					}
				}

				echo '</ul>';
			}
		}

		?>
		</ul>
		<?php
		// Paginación
		$totalPaginas = "";
		foreach ($total as $t) {
			$totalPaginas = $t / 5;
			$totalPaginas = ceil($totalPaginas);
		}
		//echo $totalPaginas;	
		?>
		<nav id="paginacion">
			<ul>
				<?php for($i=1;$i<=$totalPaginas;$i++) { 
					if($i==1) {
						echo '<a href="index.php?pagina=1"> << </a>';
						echo '<a href="index.php?pagina='.($npagina - 1).'"> < </a>';
						echo '<a href="index.php?pagina='.($i).'"> '.($i).' </a>';
					}else if($i>1 && $i<$totalPaginas){ 
						echo '<a href="index.php?pagina='.($i).'"> '.($i).' </a>';
					}else if ($i==$totalPaginas) {
						echo '<a href="index.php?pagina='.($i).'"> '.($i).' </a>';
						echo '<a href="index.php?pagina='.($npagina + 1).'"> > </a>';
						echo '<a href="index.php?pagina='.$totalPaginas.'"> >> </a>';
					}
				} ?>
				
			</ul>
		</nav>
	</body>
</html>