CREATE DATABASE Videoclub;

CREATE TABLE SOCIOS (
	NUMERO INT AUTO_INCREMENT,
	DNI VARCHAR(9),
	NOMBRE VARCHAR(30),
	APELLIDOS VARCHAR(30),
	TELÉFONO VARCHAR(20),
	PRIMARY KEY (NUMERO)
);

CREATE TABLE PELÍCULAS (
	CÓDIGO INT,
	TÍTULO VARCHAR(30),
	GÉNERO VARCHAR(30),
	NUM_SOCIO INT,
	PRIMARY KEY (CÓDIGO),
	FOREIGN KEY (NUM_SOCIO) REFERENCES SOCIOS (NUMERO)
		ON DELETE SET NULL
		ON UPDATE SET NULL
);

CREATE TABLE PRÉSTAMOS (
	NUM_SOCIO INT,
	COD_PELÍCULA INT,
	FECHA DATE,
	PRIMARY KEY (NUM_SOCIO, COD_PELÍCULA, FECHA),
	FOREIGN KEY (NUM_SOCIO) REFERENCES SOCIOS (NUMERO),
	FOREIGN KEY (COD_PELÍCULA) REFERENCES PELÍCULAS (CÓDIGO)
);