<!DOCTYPE html>
<html>
<head>
	<title>Mi lista de peliculas</title>
</head>
<body>

	<?php 

	if(isset($_SESSION['error'])){
		echo '<script >alert("'.$_SESSION['error'].'")</script>';
		unset($_SESSION['error']);
	}
	//var_dump($_SESSION['u']);

	if(!$_SESSION['u']){
		?>
	<form action="index.php?user" method="post">
		<input type="text" name="username" placeholder="nombre de usuario">
		<input type="password" name="password" placeholder="Contraseña">
		<input type="submit" value="Entrar">
	</form>
	<a href="index.php?user&register">Registrarme</a>

	<?php 
	}
	else {
	
	echo '<h2>Hola '.$_SESSION['u']->getUsername().' - <a href="index.php?user&logout">Salir</a></h2>';
	
	}
	?>
<h1>Mi lista de peliculas</h1>

<form action="index.php" method="post">
	<input type="text" name="busca" placeholder="Titulo para la búsqueda">
	<input type="submit" value="Busca">
</form>

<ul>
<?php

foreach ($movies as $movie) {
	echo '<li>'.$movie->getTitle().' (Estrenado en '.$movie->getYear().')</li>';
}

?>
</ul>
</body>
</html>