<!DOCTYPE html>
<html>
	<head>
		<title>Mi lista de viedeojuegos</title>
	</head>
	<body>
		<h1>Mi lista de videojuegos:</h1>

		<form action="index.php" method="post">
			<input type="text" name="buscar" placeholder="Título para la búsqueda">
			<input type="submit" name="Buscar" placeholder="Buscar">
		</form>

		<ul>
		<?php
		foreach ($games as $game) {
			echo '<li>'.$game->getTitle().' (Fecha de lanzamiento en '.$game->getYear().')</li>';
			echo '<img href="'.$game->getImg().'">';
		}
		?>
		</ul>
	</body>
</html>