<!DOCTYPE html>
<html lang="es">
<head>
	<title>Noticias</title>
	<meta charset="utf-8"/>
</head>
<body>
	<?php 

	// Mensaje error al inicio de sesión
	if(isset($_SESSION['error'])){
		echo '<script >alert("'.$_SESSION['error'].'")</script>';
		unset($_SESSION['error']);
	}

	// Login del usuario
	if(!$_SESSION['user']) {
		?>
		<form action="index.php?user" method="post">
			<input type="text" name="username" placeholder="nombre de usuario">
			<input type="password" name="password" placeholder="Contraseña">
			<input type="submit" value="Entrar">
		</form>
		<a href="index.php?user&register">Registrarme</a>

		<?php
	}else {
		
		echo '<h2>Bienvenido '.$_SESSION['user']->username.' - Rol: '.$_SESSION['user']->rol.' - <a href="index.php?user&logout">Salir</a></h2>';

		// Crear noticia
		?>
		<h1>Crear noticias:</h1>
		<form action="index.php?new&create" method="post">
			<input type="text" name="new" placeholder="Noticia">
			<br>
			<input type="url" name="url" placeholder="Enlace noticia">
			<br>
			<input type="submit" value="Enviar">
		</form>
		<br>
	<?php
	}
	?>
		<ul>
		<?php
			// Publicar noticias
			foreach ($news as $new) {
				echo 'Titulo: <a href="'.$new->enlace.'">'.$new->titulo.'</a> - Usuario: '.$new->username_user.'';

				// Seguridas para valoraciones
		        if($_SESSION['user'] == TRUE) {
		        	if($_SESSION['user']->rol == "admin"){
						echo ' <span><a href="index.php?delete='.$new->id.'"> X </a></span>';
			        }

			        // Mostrar valoraciones
			        if($_SESSION['user']->rol == "normal" || $_SESSION['user']->rol == "admin"){
			        	echo '<br/>';
				        if(isset($_SESSION['user'])) {
				        	echo '<a href="index.php?id='.$new->id.'&val=1">^</a>'.$new->positives.
					        '<a href="index.php?id='.$new->id.'&val=-1">v</a>'.$new->negatives.'<br><br>';
					    }else {
					    	echo $new->positives." - ".$new->negatives.'<br><br>';
						}
			        }
		        }else {
					echo '<br/>';
		        }
		        
			}
		?>
		</ul> 
</body>
</html>