<!DOCTYPE html>
<html>
<head>
	<title>registrate</title>
</head>
<body>
<h1>REGISTRO</h1>
<form action="index.php?user" method="post">
	<input type="text" name="newusername" placeholder="Nombre de usuario" required>
	<input type="password" name="password1" placeholder="Contraseña" required>
	<input type="password" name="password2" placeholder="Repite la Contraseña" required>
	<input type="submit" value="Registrar">

</form>
</body>
</html>