CREATE DATABASE VIDEOJUEGOS;

CREATE TABLE login (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER VARCHAR(50),
	PASSWORD VARCHAR(20)
);

CREATE TABLE games (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(30),
	YEAR DATE,
	IMG VARCHAR(1000)
);